api_platform:
    defaults:
        pagination_enabled: true
        pagination_items_per_page: 5
    collection:
        pagination:
            enabled_parameter_name: pagination # optional
    metadata_backward_compatibility_layer: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']
        html:
            mime_types: ['text/html']
        multipart:
            mime_types: ['multipart/form-data']
    patch_formats:
        json: ['application/merge-patch+json']
        multipart: ['multipart/form-data']
    swagger:
        versions: [3]
    