# gesdinet_jwt_refresh_token:
#     refresh_token_class: App\Entity\RefreshToken
gesdinet_jwt_refresh_token: 
    ttl: 2592000
    user_identity_field: id
    user_provider: security.user.provider.concrete.app_user_provider